apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustervigil-service-account
  namespace: test-listener

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustervigil-cluster-role
  namespace: test-listener
rules:
- apiGroups: ["*"] 
  resources: ["*"] 
  verbs: ["get", "list", "watch", "patch"]  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustervigil-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: clustervigil-service-account
  namespace: test-listener
roleRef:
  kind: ClusterRole
  name: clustervigil-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustervigil
  namespace: test-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustervigil
  template:
    metadata:
      labels:
        app: clustervigil
    spec:
      serviceAccountName: clustervigil-service-account
      containers:
      - name: clustervigil
        image: docker.io/ralls0/k8s-clustervigil-chatbot:###IMAGE_TAG###
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: genai-env
      imagePullSecrets:
      - name: regcred