apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ###PVCNAMEID###
  namespace: ###NAMESPACE###
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ###STORAGESIZE###
  storageClassName: default
